### ISSUE TITLE
Raw Data

### ISSUE THREAD

**Issue by mdmorant93** [kelron1/FMScouting#2]
Hi, would it be possible for you to commit the raw data in .csv or .json form? I'd like to play around myself with the data (my particular use case involves creating a ranking system for youth academies based off of their facilities, coaching, recruitment, etc. and then applying a multiplier based on region, as a proxy for cost).

**Comment by kelron1** [comment]
Hey, I've uploaded it to drive due to size: [link](https://drive.google.com/file/d/1Gyto5KDYFk_hJr73dsJ-DcN9Hexx34En/view?usp=sharing).

A few notes on the data:

It was all done before the winter update so it's possible there's been some changes to starting facilities & youth ratings, I don't know if SI update these mid-season.

The files labelled large-none-all are probably your best bet for a large set of players generated under the same conditions (large database - no leagues loaded - all extra players loaded). There's also large-playable-topint (all leagues playable - top division & international players loaded). 

The "start" files contain the starting player database for each setup. These include some pre-generated newgens you may want to filter out of the sim exports. 

Some nations have a disproportionate number of newgens (Brazil, Australia, USA, China and some others). These are the countries with later intakes, so the rejected trialists haven't retired from the game yet at the time of export. In theory it shouldn't make much or any difference to the numbers of higher potential youth.

**Comment by mdmorant93** [comment]
Fantastic, thank you!
